# Generated by Django 3.2.20 on 2023-08-12 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
